// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type RegistryACLInitParameters struct {

	// (Boolean) When set to true, allows the resource to be removed from state even if deletion fails due to permission errors
	// When set to true, allows the resource to be removed from state even if deletion fails due to permission errors
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// (String) The ID of the cluster where the Schema Registry ACL will be created
	// The ID of the cluster where the Schema Registry ACL will be created
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The host address to use for this ACL. Use '*' for wildcard
	// The host address to use for this ACL. Use '*' for wildcard
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) The operation type that shall be allowed or denied: ALL, READ, WRITE, DELETE, DESCRIBE, DESCRIBE_CONFIGS, ALTER, ALTER_CONFIGS
	// The operation type that shall be allowed or denied: ALL, READ, WRITE, DELETE, DESCRIBE, DESCRIBE_CONFIGS, ALTER, ALTER_CONFIGS
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// (String, Sensitive) Password for authentication. Can be set via REDPANDA_SR_PASSWORD environment variable
	// Password for authentication. Can be set via REDPANDA_SR_PASSWORD environment variable
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) The pattern type of the resource: LITERAL or PREFIXED
	// The pattern type of the resource: LITERAL or PREFIXED
	PatternType *string `json:"patternType,omitempty" tf:"pattern_type,omitempty"`

	// (String) The permission type: ALLOW or DENY
	// The permission type: ALLOW or DENY
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (String) The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)
	// The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// (String) The name of the resource this ACL entry will be on. Use '*' for wildcard
	// The name of the resource this ACL entry will be on. Use '*' for wildcard
	ResourceName *string `json:"resourceName,omitempty" tf:"resource_name,omitempty"`

	// (String) The type of the resource: SUBJECT or REGISTRY
	// The type of the resource: SUBJECT or REGISTRY
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// (String, Sensitive) Username for authentication. Can be set via REDPANDA_SR_USERNAME environment variable
	// Username for authentication. Can be set via REDPANDA_SR_USERNAME environment variable
	UsernameSecretRef *v1.SecretKeySelector `json:"usernameSecretRef,omitempty" tf:"-"`
}

type RegistryACLObservation struct {

	// (Boolean) When set to true, allows the resource to be removed from state even if deletion fails due to permission errors
	// When set to true, allows the resource to be removed from state even if deletion fails due to permission errors
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// (String) The ID of the cluster where the Schema Registry ACL will be created
	// The ID of the cluster where the Schema Registry ACL will be created
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The host address to use for this ACL. Use '*' for wildcard
	// The host address to use for this ACL. Use '*' for wildcard
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The operation type that shall be allowed or denied: ALL, READ, WRITE, DELETE, DESCRIBE, DESCRIBE_CONFIGS, ALTER, ALTER_CONFIGS
	// The operation type that shall be allowed or denied: ALL, READ, WRITE, DELETE, DESCRIBE, DESCRIBE_CONFIGS, ALTER, ALTER_CONFIGS
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// (String) The pattern type of the resource: LITERAL or PREFIXED
	// The pattern type of the resource: LITERAL or PREFIXED
	PatternType *string `json:"patternType,omitempty" tf:"pattern_type,omitempty"`

	// (String) The permission type: ALLOW or DENY
	// The permission type: ALLOW or DENY
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (String) The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)
	// The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// (String) The name of the resource this ACL entry will be on. Use '*' for wildcard
	// The name of the resource this ACL entry will be on. Use '*' for wildcard
	ResourceName *string `json:"resourceName,omitempty" tf:"resource_name,omitempty"`

	// (String) The type of the resource: SUBJECT or REGISTRY
	// The type of the resource: SUBJECT or REGISTRY
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`
}

type RegistryACLParameters struct {

	// (Boolean) When set to true, allows the resource to be removed from state even if deletion fails due to permission errors
	// When set to true, allows the resource to be removed from state even if deletion fails due to permission errors
	// +kubebuilder:validation:Optional
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// (String) The ID of the cluster where the Schema Registry ACL will be created
	// The ID of the cluster where the Schema Registry ACL will be created
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The host address to use for this ACL. Use '*' for wildcard
	// The host address to use for this ACL. Use '*' for wildcard
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String) The operation type that shall be allowed or denied: ALL, READ, WRITE, DELETE, DESCRIBE, DESCRIBE_CONFIGS, ALTER, ALTER_CONFIGS
	// The operation type that shall be allowed or denied: ALL, READ, WRITE, DELETE, DESCRIBE, DESCRIBE_CONFIGS, ALTER, ALTER_CONFIGS
	// +kubebuilder:validation:Optional
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// (String, Sensitive) Password for authentication. Can be set via REDPANDA_SR_PASSWORD environment variable
	// Password for authentication. Can be set via REDPANDA_SR_PASSWORD environment variable
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) The pattern type of the resource: LITERAL or PREFIXED
	// The pattern type of the resource: LITERAL or PREFIXED
	// +kubebuilder:validation:Optional
	PatternType *string `json:"patternType,omitempty" tf:"pattern_type,omitempty"`

	// (String) The permission type: ALLOW or DENY
	// The permission type: ALLOW or DENY
	// +kubebuilder:validation:Optional
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (String) The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)
	// The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// (String) The name of the resource this ACL entry will be on. Use '*' for wildcard
	// The name of the resource this ACL entry will be on. Use '*' for wildcard
	// +kubebuilder:validation:Optional
	ResourceName *string `json:"resourceName,omitempty" tf:"resource_name,omitempty"`

	// (String) The type of the resource: SUBJECT or REGISTRY
	// The type of the resource: SUBJECT or REGISTRY
	// +kubebuilder:validation:Optional
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// (String, Sensitive) Username for authentication. Can be set via REDPANDA_SR_USERNAME environment variable
	// Username for authentication. Can be set via REDPANDA_SR_USERNAME environment variable
	// +kubebuilder:validation:Optional
	UsernameSecretRef *v1.SecretKeySelector `json:"usernameSecretRef,omitempty" tf:"-"`
}

// RegistryACLSpec defines the desired state of RegistryACL
type RegistryACLSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RegistryACLParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RegistryACLInitParameters `json:"initProvider,omitempty"`
}

// RegistryACLStatus defines the observed state of RegistryACL.
type RegistryACLStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RegistryACLObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RegistryACL is the Schema for the RegistryACLs API. Resource for managing Redpanda Schema Registry ACLs (Access Control Lists). This resource allows you to configure fine-grained access control for Schema Registry resources.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,redpanda}
type RegistryACL struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.host) || (has(self.initProvider) && has(self.initProvider.host))",message="spec.forProvider.host is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.operation) || (has(self.initProvider) && has(self.initProvider.operation))",message="spec.forProvider.operation is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.patternType) || (has(self.initProvider) && has(self.initProvider.patternType))",message="spec.forProvider.patternType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permission) || (has(self.initProvider) && has(self.initProvider.permission))",message="spec.forProvider.permission is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.principal) || (has(self.initProvider) && has(self.initProvider.principal))",message="spec.forProvider.principal is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resourceName) || (has(self.initProvider) && has(self.initProvider.resourceName))",message="spec.forProvider.resourceName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resourceType) || (has(self.initProvider) && has(self.initProvider.resourceType))",message="spec.forProvider.resourceType is a required parameter"
	Spec   RegistryACLSpec   `json:"spec"`
	Status RegistryACLStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RegistryACLList contains a list of RegistryACLs
type RegistryACLList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RegistryACL `json:"items"`
}

// Repository type metadata.
var (
	RegistryACL_Kind             = "RegistryACL"
	RegistryACL_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RegistryACL_Kind}.String()
	RegistryACL_KindAPIVersion   = RegistryACL_Kind + "." + CRDGroupVersion.String()
	RegistryACL_GroupVersionKind = CRDGroupVersion.WithKind(RegistryACL_Kind)
)

func init() {
	SchemeBuilder.Register(&RegistryACL{}, &RegistryACLList{})
}
