// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AgentInstanceProfileInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the agent instance profile
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type AgentInstanceProfileObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the agent instance profile
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type AgentInstanceProfileParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the agent instance profile
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type AgentServiceAccountInitParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type AgentServiceAccountObservation struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type AgentServiceAccountParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type AwsInitParameters struct {

	// (Attributes) (see below for nested schema)
	AgentInstanceProfile *AgentInstanceProfileInitParameters `json:"agentInstanceProfile,omitempty" tf:"agent_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	CloudStorageBucket *CloudStorageBucketInitParameters `json:"cloudStorageBucket,omitempty" tf:"cloud_storage_bucket,omitempty"`

	// (Attributes) (see below for nested schema)
	ClusterSecurityGroup *ClusterSecurityGroupInitParameters `json:"clusterSecurityGroup,omitempty" tf:"cluster_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	ConnectorsNodeGroupInstanceProfile *ConnectorsNodeGroupInstanceProfileInitParameters `json:"connectorsNodeGroupInstanceProfile,omitempty" tf:"connectors_node_group_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	ConnectorsSecurityGroup *ConnectorsSecurityGroupInitParameters `json:"connectorsSecurityGroup,omitempty" tf:"connectors_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	K8SClusterRole *K8SClusterRoleInitParameters `json:"k8sClusterRole,omitempty" tf:"k8s_cluster_role,omitempty"`

	// (Attributes) (see below for nested schema)
	NodeSecurityGroup *NodeSecurityGroupInitParameters `json:"nodeSecurityGroup,omitempty" tf:"node_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	PermissionsBoundaryPolicy *PermissionsBoundaryPolicyInitParameters `json:"permissionsBoundaryPolicy,omitempty" tf:"permissions_boundary_policy,omitempty"`

	// (Attributes) (see below for nested schema)
	RedpandaAgentSecurityGroup *RedpandaAgentSecurityGroupInitParameters `json:"redpandaAgentSecurityGroup,omitempty" tf:"redpanda_agent_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	RedpandaNodeGroupInstanceProfile *RedpandaNodeGroupInstanceProfileInitParameters `json:"redpandaNodeGroupInstanceProfile,omitempty" tf:"redpanda_node_group_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	RedpandaNodeGroupSecurityGroup *RedpandaNodeGroupSecurityGroupInitParameters `json:"redpandaNodeGroupSecurityGroup,omitempty" tf:"redpanda_node_group_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	UtilityNodeGroupInstanceProfile *UtilityNodeGroupInstanceProfileInitParameters `json:"utilityNodeGroupInstanceProfile,omitempty" tf:"utility_node_group_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	UtilitySecurityGroup *UtilitySecurityGroupInitParameters `json:"utilitySecurityGroup,omitempty" tf:"utility_security_group,omitempty"`
}

type AwsObservation struct {

	// (Attributes) (see below for nested schema)
	AgentInstanceProfile *AgentInstanceProfileObservation `json:"agentInstanceProfile,omitempty" tf:"agent_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	CloudStorageBucket *CloudStorageBucketObservation `json:"cloudStorageBucket,omitempty" tf:"cloud_storage_bucket,omitempty"`

	// (Attributes) (see below for nested schema)
	ClusterSecurityGroup *ClusterSecurityGroupObservation `json:"clusterSecurityGroup,omitempty" tf:"cluster_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	ConnectorsNodeGroupInstanceProfile *ConnectorsNodeGroupInstanceProfileObservation `json:"connectorsNodeGroupInstanceProfile,omitempty" tf:"connectors_node_group_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	ConnectorsSecurityGroup *ConnectorsSecurityGroupObservation `json:"connectorsSecurityGroup,omitempty" tf:"connectors_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	K8SClusterRole *K8SClusterRoleObservation `json:"k8sClusterRole,omitempty" tf:"k8s_cluster_role,omitempty"`

	// (Attributes) (see below for nested schema)
	NodeSecurityGroup *NodeSecurityGroupObservation `json:"nodeSecurityGroup,omitempty" tf:"node_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	PermissionsBoundaryPolicy *PermissionsBoundaryPolicyObservation `json:"permissionsBoundaryPolicy,omitempty" tf:"permissions_boundary_policy,omitempty"`

	// (Attributes) (see below for nested schema)
	RedpandaAgentSecurityGroup *RedpandaAgentSecurityGroupObservation `json:"redpandaAgentSecurityGroup,omitempty" tf:"redpanda_agent_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	RedpandaNodeGroupInstanceProfile *RedpandaNodeGroupInstanceProfileObservation `json:"redpandaNodeGroupInstanceProfile,omitempty" tf:"redpanda_node_group_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	RedpandaNodeGroupSecurityGroup *RedpandaNodeGroupSecurityGroupObservation `json:"redpandaNodeGroupSecurityGroup,omitempty" tf:"redpanda_node_group_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	UtilityNodeGroupInstanceProfile *UtilityNodeGroupInstanceProfileObservation `json:"utilityNodeGroupInstanceProfile,omitempty" tf:"utility_node_group_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	UtilitySecurityGroup *UtilitySecurityGroupObservation `json:"utilitySecurityGroup,omitempty" tf:"utility_security_group,omitempty"`
}

type AwsParameters struct {

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	AgentInstanceProfile *AgentInstanceProfileParameters `json:"agentInstanceProfile" tf:"agent_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	CloudStorageBucket *CloudStorageBucketParameters `json:"cloudStorageBucket" tf:"cloud_storage_bucket,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	ClusterSecurityGroup *ClusterSecurityGroupParameters `json:"clusterSecurityGroup" tf:"cluster_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	ConnectorsNodeGroupInstanceProfile *ConnectorsNodeGroupInstanceProfileParameters `json:"connectorsNodeGroupInstanceProfile" tf:"connectors_node_group_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	ConnectorsSecurityGroup *ConnectorsSecurityGroupParameters `json:"connectorsSecurityGroup" tf:"connectors_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	K8SClusterRole *K8SClusterRoleParameters `json:"k8sClusterRole" tf:"k8s_cluster_role,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	NodeSecurityGroup *NodeSecurityGroupParameters `json:"nodeSecurityGroup" tf:"node_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	PermissionsBoundaryPolicy *PermissionsBoundaryPolicyParameters `json:"permissionsBoundaryPolicy" tf:"permissions_boundary_policy,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	RedpandaAgentSecurityGroup *RedpandaAgentSecurityGroupParameters `json:"redpandaAgentSecurityGroup" tf:"redpanda_agent_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	RedpandaNodeGroupInstanceProfile *RedpandaNodeGroupInstanceProfileParameters `json:"redpandaNodeGroupInstanceProfile" tf:"redpanda_node_group_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	RedpandaNodeGroupSecurityGroup *RedpandaNodeGroupSecurityGroupParameters `json:"redpandaNodeGroupSecurityGroup" tf:"redpanda_node_group_security_group,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	UtilityNodeGroupInstanceProfile *UtilityNodeGroupInstanceProfileParameters `json:"utilityNodeGroupInstanceProfile" tf:"utility_node_group_instance_profile,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	UtilitySecurityGroup *UtilitySecurityGroupParameters `json:"utilitySecurityGroup" tf:"utility_security_group,omitempty"`
}

type AwsPrivateLinkInitParameters struct {

	// (List of String) The ARN of the principals that can access the Redpanda AWS PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	// The ARN of the principals that can access the Redpanda AWS PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	AllowedPrincipals []*string `json:"allowedPrincipals,omitempty" tf:"allowed_principals,omitempty"`

	// (Boolean) Whether Console is connected via PrivateLink.
	// Whether Console is connected via PrivateLink.
	ConnectConsole *bool `json:"connectConsole,omitempty" tf:"connect_console,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether AWS PrivateLink is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type AwsPrivateLinkObservation struct {

	// (List of String) The ARN of the principals that can access the Redpanda AWS PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	// The ARN of the principals that can access the Redpanda AWS PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	AllowedPrincipals []*string `json:"allowedPrincipals,omitempty" tf:"allowed_principals,omitempty"`

	// (Boolean) Whether Console is connected via PrivateLink.
	// Whether Console is connected via PrivateLink.
	ConnectConsole *bool `json:"connectConsole,omitempty" tf:"connect_console,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether AWS PrivateLink is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) Current status of the PrivateLink configuration. (see below for nested schema)
	Status *StatusObservation `json:"status,omitempty" tf:"status,omitempty"`
}

type AwsPrivateLinkParameters struct {

	// (List of String) The ARN of the principals that can access the Redpanda AWS PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	// The ARN of the principals that can access the Redpanda AWS PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	// +kubebuilder:validation:Optional
	AllowedPrincipals []*string `json:"allowedPrincipals" tf:"allowed_principals,omitempty"`

	// (Boolean) Whether Console is connected via PrivateLink.
	// Whether Console is connected via PrivateLink.
	// +kubebuilder:validation:Optional
	ConnectConsole *bool `json:"connectConsole" tf:"connect_console,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether AWS PrivateLink is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`
}

type AzurePrivateLinkInitParameters struct {

	// (List of String) The subscriptions that can access the Redpanda Azure PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	// The subscriptions that can access the Redpanda Azure PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	AllowedSubscriptions []*string `json:"allowedSubscriptions,omitempty" tf:"allowed_subscriptions,omitempty"`

	// (Boolean) Whether Console is connected via PrivateLink.
	// Whether Console is connected in Redpanda Azure Private Link Service.
	ConnectConsole *bool `json:"connectConsole,omitempty" tf:"connect_console,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether Redpanda Azure Private Link Endpoint Service is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type AzurePrivateLinkObservation struct {

	// (List of String) The subscriptions that can access the Redpanda Azure PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	// The subscriptions that can access the Redpanda Azure PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	AllowedSubscriptions []*string `json:"allowedSubscriptions,omitempty" tf:"allowed_subscriptions,omitempty"`

	// (Boolean) Whether Console is connected via PrivateLink.
	// Whether Console is connected in Redpanda Azure Private Link Service.
	ConnectConsole *bool `json:"connectConsole,omitempty" tf:"connect_console,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether Redpanda Azure Private Link Endpoint Service is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) Current status of the PrivateLink configuration. (see below for nested schema)
	Status *AzurePrivateLinkStatusObservation `json:"status,omitempty" tf:"status,omitempty"`
}

type AzurePrivateLinkParameters struct {

	// (List of String) The subscriptions that can access the Redpanda Azure PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	// The subscriptions that can access the Redpanda Azure PrivateLink Endpoint Service. To grant permissions to all principals, use an asterisk (*).
	// +kubebuilder:validation:Optional
	AllowedSubscriptions []*string `json:"allowedSubscriptions" tf:"allowed_subscriptions,omitempty"`

	// (Boolean) Whether Console is connected via PrivateLink.
	// Whether Console is connected in Redpanda Azure Private Link Service.
	// +kubebuilder:validation:Optional
	ConnectConsole *bool `json:"connectConsole" tf:"connect_console,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether Redpanda Azure Private Link Endpoint Service is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`
}

type AzurePrivateLinkStatusInitParameters struct {
}

type AzurePrivateLinkStatusObservation struct {

	// (List of String) List of approved Azure subscription IDs.
	// List of approved Azure subscription IDs.
	ApprovedSubscriptions []*string `json:"approvedSubscriptions,omitempty" tf:"approved_subscriptions,omitempty"`

	// (Number) Port for Redpanda Console.
	// Port for Redpanda Console.
	ConsolePort *float64 `json:"consolePort,omitempty" tf:"console_port,omitempty"`

	// (String) Timestamp when the cluster was created.
	// When the Private Link service was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) DNS A record for the service.
	// DNS A record for the service.
	DNSARecord *string `json:"dnsARecord,omitempty" tf:"dns_a_record,omitempty"`

	// (String) When the PrivateLink service was deleted.
	// When the Private Link service was deleted.
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// (Number) Base port for Kafka API nodes.
	// Base port for Kafka API nodes.
	KafkaAPINodeBasePort *float64 `json:"kafkaApiNodeBasePort,omitempty" tf:"kafka_api_node_base_port,omitempty"`

	// (Number) Port for Kafka API seed brokers.
	// Port for Kafka API seed brokers.
	KafkaAPISeedPort *float64 `json:"kafkaApiSeedPort,omitempty" tf:"kafka_api_seed_port,omitempty"`

	// (Attributes List) List of private endpoint connections. (see below for nested schema)
	PrivateEndpointConnections []PrivateEndpointConnectionsObservation `json:"privateEndpointConnections,omitempty" tf:"private_endpoint_connections,omitempty"`

	// (Number) Base port for HTTP proxy nodes.
	// Base port for HTTP proxy nodes.
	RedpandaProxyNodeBasePort *float64 `json:"redpandaProxyNodeBasePort,omitempty" tf:"redpanda_proxy_node_base_port,omitempty"`

	// (Number) Port for HTTP proxy.
	// Port for HTTP proxy.
	RedpandaProxySeedPort *float64 `json:"redpandaProxySeedPort,omitempty" tf:"redpanda_proxy_seed_port,omitempty"`

	// (Number) Port for Schema Registry.
	// Port for Schema Registry.
	SchemaRegistrySeedPort *float64 `json:"schemaRegistrySeedPort,omitempty" tf:"schema_registry_seed_port,omitempty"`

	// (String) The PrivateLink service ID.
	// The Private Link service ID.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) The PrivateLink service name.
	// The Private Link service name.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type AzurePrivateLinkStatusParameters struct {
}

type CloudStorageBucketInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the cloud storage bucket
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type CloudStorageBucketObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the cloud storage bucket
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type CloudStorageBucketParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the cloud storage bucket
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type ClusterConfigurationInitParameters struct {

	// (String) Custom properties for the cluster in JSON format.
	// Custom properties for the cluster in JSON format.
	CustomPropertiesJSON *string `json:"customPropertiesJson,omitempty" tf:"custom_properties_json,omitempty"`
}

type ClusterConfigurationObservation struct {

	// (String) Custom properties for the cluster in JSON format.
	// Custom properties for the cluster in JSON format.
	CustomPropertiesJSON *string `json:"customPropertiesJson,omitempty" tf:"custom_properties_json,omitempty"`
}

type ClusterConfigurationParameters struct {

	// (String) Custom properties for the cluster in JSON format.
	// Custom properties for the cluster in JSON format.
	// +kubebuilder:validation:Optional
	CustomPropertiesJSON *string `json:"customPropertiesJson,omitempty" tf:"custom_properties_json,omitempty"`
}

type ClusterInitParameters struct {

	// (Boolean) Allows deletion of the cluster. Defaults to false.
	// Allows deletion of the cluster. Defaults to false.
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// (Attributes) AWS PrivateLink configuration. (see below for nested schema)
	AwsPrivateLink *AwsPrivateLinkInitParameters `json:"awsPrivateLink,omitempty" tf:"aws_private_link,omitempty"`

	// (Attributes) Azure Private Link configuration. (see below for nested schema)
	AzurePrivateLink *AzurePrivateLinkInitParameters `json:"azurePrivateLink,omitempty" tf:"azure_private_link,omitempty"`

	// (String) Cloud provider where resources are created.
	// Cloud provider where resources are created.
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (Attributes) Configuration for the cluster. (see below for nested schema)
	ClusterConfiguration *ClusterConfigurationInitParameters `json:"clusterConfiguration,omitempty" tf:"cluster_configuration,omitempty"`

	// (String) Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	// Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// practice.
	// Cluster connection type. Private clusters are not exposed to the internet. For BYOC clusters, private is best-practice.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// (Attributes) Customer managed resources configuration for the cluster. (see below for nested schema)
	CustomerManagedResources *CustomerManagedResourcesInitParameters `json:"customerManagedResources,omitempty" tf:"customer_managed_resources,omitempty"`

	// (Boolean) If true, GCP global access is enabled.
	// If true, GCP global access is enabled.
	GCPGlobalAccessEnabled *bool `json:"gcpGlobalAccessEnabled,omitempty" tf:"gcp_global_access_enabled,omitempty"`

	// (Attributes) GCP Private Service Connect configuration. (see below for nested schema)
	GCPPrivateServiceConnect *GCPPrivateServiceConnectInitParameters `json:"gcpPrivateServiceConnect,omitempty" tf:"gcp_private_service_connect,omitempty"`

	// (Attributes) HTTP Proxy properties. (see below for nested schema)
	HTTPProxy *HTTPProxyInitParameters `json:"httpProxy,omitempty" tf:"http_proxy,omitempty"`

	// (Attributes) Cluster's Kafka API properties. (see below for nested schema)
	KafkaAPI *KafkaAPIInitParameters `json:"kafkaApi,omitempty" tf:"kafka_api,omitempty"`

	// (Attributes) Kafka Connect configuration. (see below for nested schema)
	KafkaConnect *KafkaConnectInitParameters `json:"kafkaConnect,omitempty" tf:"kafka_connect,omitempty"`

	// (Attributes) Maintenance window configuration for the cluster. (see below for nested schema)
	MaintenanceWindowConfig *MaintenanceWindowConfigInitParameters `json:"maintenanceWindowConfig,omitempty" tf:"maintenance_window_config,omitempty"`

	// (String) Unique name of the cluster.
	// Unique name of the cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Network ID where cluster is placed.
	// Network ID where cluster is placed.
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// only topics from this cluster.
	// IDs of clusters that can create read-only topics from this cluster.
	ReadReplicaClusterIds []*string `json:"readReplicaClusterIds,omitempty" tf:"read_replica_cluster_ids,omitempty"`

	// (String) Current Redpanda version of the cluster.
	// Current Redpanda version of the cluster.
	RedpandaVersion *string `json:"redpandaVersion,omitempty" tf:"redpanda_version,omitempty"`

	// (String) Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	// Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Resource group ID of the cluster.
	// Resource group ID of the cluster.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// (Attributes) Schema Registry properties. (see below for nested schema)
	SchemaRegistry *SchemaRegistryInitParameters `json:"schemaRegistry,omitempty" tf:"schema_registry,omitempty"`

	// tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	// Tags placed on cloud resources. If the cloud provider is GCP and the name of a tag has the prefix "gcp.network-tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Usage tier of the cluster. WARNING: Do not modify after it is set.
	ThroughputTier *string `json:"throughputTier,omitempty" tf:"throughput_tier,omitempty"`

	// (Attributes) (see below for nested schema)
	Timeouts *TimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// AZ cluster.
	// Zones of the cluster. Must be valid zones within the selected region. If multiple zones are used, the cluster is a multi-AZ cluster.
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type ClusterObservation struct {

	// (Boolean) Allows deletion of the cluster. Defaults to false.
	// Allows deletion of the cluster. Defaults to false.
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// (Attributes) AWS PrivateLink configuration. (see below for nested schema)
	AwsPrivateLink *AwsPrivateLinkObservation `json:"awsPrivateLink,omitempty" tf:"aws_private_link,omitempty"`

	// (Attributes) Azure Private Link configuration. (see below for nested schema)
	AzurePrivateLink *AzurePrivateLinkObservation `json:"azurePrivateLink,omitempty" tf:"azure_private_link,omitempty"`

	// (String) Cloud provider where resources are created.
	// Cloud provider where resources are created.
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String) The URL of the cluster API.
	// The URL of the cluster API.
	ClusterAPIURL *string `json:"clusterApiUrl,omitempty" tf:"cluster_api_url,omitempty"`

	// (Attributes) Configuration for the cluster. (see below for nested schema)
	ClusterConfiguration *ClusterConfigurationObservation `json:"clusterConfiguration,omitempty" tf:"cluster_configuration,omitempty"`

	// (String) Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	// Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// practice.
	// Cluster connection type. Private clusters are not exposed to the internet. For BYOC clusters, private is best-practice.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// (String) Timestamp when the cluster was created.
	// Timestamp when the cluster was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Attributes) Customer managed resources configuration for the cluster. (see below for nested schema)
	CustomerManagedResources *CustomerManagedResourcesObservation `json:"customerManagedResources,omitempty" tf:"customer_managed_resources,omitempty"`

	// (Boolean) If true, GCP global access is enabled.
	// If true, GCP global access is enabled.
	GCPGlobalAccessEnabled *bool `json:"gcpGlobalAccessEnabled,omitempty" tf:"gcp_global_access_enabled,omitempty"`

	// (Attributes) GCP Private Service Connect configuration. (see below for nested schema)
	GCPPrivateServiceConnect *GCPPrivateServiceConnectObservation `json:"gcpPrivateServiceConnect,omitempty" tf:"gcp_private_service_connect,omitempty"`

	// (Attributes) HTTP Proxy properties. (see below for nested schema)
	HTTPProxy *HTTPProxyObservation `json:"httpProxy,omitempty" tf:"http_proxy,omitempty"`

	// (String) ID of the cluster. ID is an output from the Create Cluster endpoint and cannot be set by the caller.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Cluster's Kafka API properties. (see below for nested schema)
	KafkaAPI *KafkaAPIObservation `json:"kafkaApi,omitempty" tf:"kafka_api,omitempty"`

	// (Attributes) Kafka Connect configuration. (see below for nested schema)
	KafkaConnect *KafkaConnectObservation `json:"kafkaConnect,omitempty" tf:"kafka_connect,omitempty"`

	// (Attributes) Maintenance window configuration for the cluster. (see below for nested schema)
	MaintenanceWindowConfig *MaintenanceWindowConfigObservation `json:"maintenanceWindowConfig,omitempty" tf:"maintenance_window_config,omitempty"`

	// (String) Unique name of the cluster.
	// Unique name of the cluster.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Network ID where cluster is placed.
	// Network ID where cluster is placed.
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (Attributes) Prometheus metrics endpoint properties. (see below for nested schema)
	Prometheus *PrometheusObservation `json:"prometheus,omitempty" tf:"prometheus,omitempty"`

	// only topics from this cluster.
	// IDs of clusters that can create read-only topics from this cluster.
	ReadReplicaClusterIds []*string `json:"readReplicaClusterIds,omitempty" tf:"read_replica_cluster_ids,omitempty"`

	// (Attributes) Redpanda Console properties. (see below for nested schema)
	RedpandaConsole *RedpandaConsoleObservation `json:"redpandaConsole,omitempty" tf:"redpanda_console,omitempty"`

	// (String) Current Redpanda version of the cluster.
	// Current Redpanda version of the cluster.
	RedpandaVersion *string `json:"redpandaVersion,omitempty" tf:"redpanda_version,omitempty"`

	// (String) Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	// Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Resource group ID of the cluster.
	// Resource group ID of the cluster.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// (Attributes) Schema Registry properties. (see below for nested schema)
	SchemaRegistry *SchemaRegistryObservation `json:"schemaRegistry,omitempty" tf:"schema_registry,omitempty"`

	// (String) Current state of the cluster.
	// Current state of the cluster.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// ready state. (see below for nested schema)
	StateDescription *StateDescriptionObservation `json:"stateDescription,omitempty" tf:"state_description,omitempty"`

	// tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	// Tags placed on cloud resources. If the cloud provider is GCP and the name of a tag has the prefix "gcp.network-tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Usage tier of the cluster. WARNING: Do not modify after it is set.
	ThroughputTier *string `json:"throughputTier,omitempty" tf:"throughput_tier,omitempty"`

	// (Attributes) (see below for nested schema)
	Timeouts *TimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// AZ cluster.
	// Zones of the cluster. Must be valid zones within the selected region. If multiple zones are used, the cluster is a multi-AZ cluster.
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type ClusterParameters struct {

	// (Boolean) Allows deletion of the cluster. Defaults to false.
	// Allows deletion of the cluster. Defaults to false.
	// +kubebuilder:validation:Optional
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// (Attributes) AWS PrivateLink configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	AwsPrivateLink *AwsPrivateLinkParameters `json:"awsPrivateLink,omitempty" tf:"aws_private_link,omitempty"`

	// (Attributes) Azure Private Link configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	AzurePrivateLink *AzurePrivateLinkParameters `json:"azurePrivateLink,omitempty" tf:"azure_private_link,omitempty"`

	// (String) Cloud provider where resources are created.
	// Cloud provider where resources are created.
	// +kubebuilder:validation:Optional
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (Attributes) Configuration for the cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ClusterConfiguration *ClusterConfigurationParameters `json:"clusterConfiguration,omitempty" tf:"cluster_configuration,omitempty"`

	// (String) Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	// Cluster type. Type is immutable and can only be set on cluster creation. Can be either byoc or dedicated.
	// +kubebuilder:validation:Optional
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// practice.
	// Cluster connection type. Private clusters are not exposed to the internet. For BYOC clusters, private is best-practice.
	// +kubebuilder:validation:Optional
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// (Attributes) Customer managed resources configuration for the cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	CustomerManagedResources *CustomerManagedResourcesParameters `json:"customerManagedResources,omitempty" tf:"customer_managed_resources,omitempty"`

	// (Boolean) If true, GCP global access is enabled.
	// If true, GCP global access is enabled.
	// +kubebuilder:validation:Optional
	GCPGlobalAccessEnabled *bool `json:"gcpGlobalAccessEnabled,omitempty" tf:"gcp_global_access_enabled,omitempty"`

	// (Attributes) GCP Private Service Connect configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	GCPPrivateServiceConnect *GCPPrivateServiceConnectParameters `json:"gcpPrivateServiceConnect,omitempty" tf:"gcp_private_service_connect,omitempty"`

	// (Attributes) HTTP Proxy properties. (see below for nested schema)
	// +kubebuilder:validation:Optional
	HTTPProxy *HTTPProxyParameters `json:"httpProxy,omitempty" tf:"http_proxy,omitempty"`

	// (Attributes) Cluster's Kafka API properties. (see below for nested schema)
	// +kubebuilder:validation:Optional
	KafkaAPI *KafkaAPIParameters `json:"kafkaApi,omitempty" tf:"kafka_api,omitempty"`

	// (Attributes) Kafka Connect configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	KafkaConnect *KafkaConnectParameters `json:"kafkaConnect,omitempty" tf:"kafka_connect,omitempty"`

	// (Attributes) Maintenance window configuration for the cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	MaintenanceWindowConfig *MaintenanceWindowConfigParameters `json:"maintenanceWindowConfig,omitempty" tf:"maintenance_window_config,omitempty"`

	// (String) Unique name of the cluster.
	// Unique name of the cluster.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Network ID where cluster is placed.
	// Network ID where cluster is placed.
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// only topics from this cluster.
	// IDs of clusters that can create read-only topics from this cluster.
	// +kubebuilder:validation:Optional
	ReadReplicaClusterIds []*string `json:"readReplicaClusterIds,omitempty" tf:"read_replica_cluster_ids,omitempty"`

	// (String) Current Redpanda version of the cluster.
	// Current Redpanda version of the cluster.
	// +kubebuilder:validation:Optional
	RedpandaVersion *string `json:"redpandaVersion,omitempty" tf:"redpanda_version,omitempty"`

	// (String) Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	// Cloud provider region. Region represents the name of the region where the cluster will be provisioned.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Resource group ID of the cluster.
	// Resource group ID of the cluster.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// (Attributes) Schema Registry properties. (see below for nested schema)
	// +kubebuilder:validation:Optional
	SchemaRegistry *SchemaRegistryParameters `json:"schemaRegistry,omitempty" tf:"schema_registry,omitempty"`

	// tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	// Tags placed on cloud resources. If the cloud provider is GCP and the name of a tag has the prefix "gcp.network-tag.", the tag is a network tag that will be added to the Redpanda cluster GKE nodes. Otherwise, the tag is a normal tag. For example, if the name of a tag is "gcp.network-tag.network-tag-foo", the network tag named "network-tag-foo" will be added to the Redpanda cluster GKE nodes. Note: The value of a network tag will be ignored. See the details on network tags at https://cloud.google.com/vpc/docs/add-remove-network-tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Usage tier of the cluster. WARNING: Do not modify after it is set.
	// +kubebuilder:validation:Optional
	ThroughputTier *string `json:"throughputTier,omitempty" tf:"throughput_tier,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Timeouts *TimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// AZ cluster.
	// Zones of the cluster. Must be valid zones within the selected region. If multiple zones are used, the cluster is a multi-AZ cluster.
	// +kubebuilder:validation:Optional
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type ClusterSecurityGroupInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the cluster security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type ClusterSecurityGroupObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the cluster security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type ClusterSecurityGroupParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the cluster security group
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type ConnectedEndpointsInitParameters struct {
}

type ConnectedEndpointsObservation struct {

	// (String) The connection ID.
	// The connection ID.
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// (String) The consumer network.
	// The consumer network.
	ConsumerNetwork *string `json:"consumerNetwork,omitempty" tf:"consumer_network,omitempty"`

	// (String) The endpoint address.
	// The endpoint address.
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// (Attributes) Current status of the PrivateLink configuration. (see below for nested schema)
	// Status of the endpoint connection.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ConnectedEndpointsParameters struct {
}

type ConnectorServiceAccountInitParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type ConnectorServiceAccountObservation struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type ConnectorServiceAccountParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type ConnectorsNodeGroupInstanceProfileInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the connectors node group instance profile
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type ConnectorsNodeGroupInstanceProfileObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the connectors node group instance profile
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type ConnectorsNodeGroupInstanceProfileParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the connectors node group instance profile
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type ConnectorsSecurityGroupInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the connectors security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type ConnectorsSecurityGroupObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the connectors security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type ConnectorsSecurityGroupParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the connectors security group
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type ConsoleServiceAccountInitParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type ConsoleServiceAccountObservation struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type ConsoleServiceAccountParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type ConsumerAcceptListInitParameters struct {

	// (String) Either the GCP project number or its alphanumeric ID.
	// Either the GCP project number or its alphanumeric ID.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ConsumerAcceptListObservation struct {

	// (String) Either the GCP project number or its alphanumeric ID.
	// Either the GCP project number or its alphanumeric ID.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ConsumerAcceptListParameters struct {

	// (String) Either the GCP project number or its alphanumeric ID.
	// Either the GCP project number or its alphanumeric ID.
	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`
}

type CustomerManagedResourcesInitParameters struct {

	// (Attributes) (see below for nested schema)
	Aws *AwsInitParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// (Attributes) (see below for nested schema)
	GCP *GCPInitParameters `json:"gcp,omitempty" tf:"gcp,omitempty"`
}

type CustomerManagedResourcesObservation struct {

	// (Attributes) (see below for nested schema)
	Aws *AwsObservation `json:"aws,omitempty" tf:"aws,omitempty"`

	// (Attributes) (see below for nested schema)
	GCP *GCPObservation `json:"gcp,omitempty" tf:"gcp,omitempty"`
}

type CustomerManagedResourcesParameters struct {

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Aws *AwsParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	GCP *GCPParameters `json:"gcp,omitempty" tf:"gcp,omitempty"`
}

type DNSEntriesInitParameters struct {
}

type DNSEntriesObservation struct {

	// (String) The DNS name.
	// The DNS name.
	DNSName *string `json:"dnsName,omitempty" tf:"dns_name,omitempty"`

	// (String) The hosted zone ID.
	// The hosted zone ID.
	HostedZoneID *string `json:"hostedZoneId,omitempty" tf:"hosted_zone_id,omitempty"`
}

type DNSEntriesParameters struct {
}

type DayHourInitParameters struct {

	// (String) Day of week.
	// Day of week.
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// (Number) Hour of day.
	// Hour of day.
	HourOfDay *float64 `json:"hourOfDay,omitempty" tf:"hour_of_day,omitempty"`
}

type DayHourObservation struct {

	// (String) Day of week.
	// Day of week.
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// (Number) Hour of day.
	// Hour of day.
	HourOfDay *float64 `json:"hourOfDay,omitempty" tf:"hour_of_day,omitempty"`
}

type DayHourParameters struct {

	// (String) Day of week.
	// Day of week.
	// +kubebuilder:validation:Optional
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// (Number) Hour of day.
	// Hour of day.
	// +kubebuilder:validation:Optional
	HourOfDay *float64 `json:"hourOfDay,omitempty" tf:"hour_of_day,omitempty"`
}

type GCPInitParameters struct {

	// (Attributes) GCP service account for the agent. (see below for nested schema)
	AgentServiceAccount *AgentServiceAccountInitParameters `json:"agentServiceAccount,omitempty" tf:"agent_service_account,omitempty"`

	// (Attributes) GCP service account for managed connectors. (see below for nested schema)
	ConnectorServiceAccount *ConnectorServiceAccountInitParameters `json:"connectorServiceAccount,omitempty" tf:"connector_service_account,omitempty"`

	// (Attributes) GCP service account for Redpanda Console. (see below for nested schema)
	ConsoleServiceAccount *ConsoleServiceAccountInitParameters `json:"consoleServiceAccount,omitempty" tf:"console_service_account,omitempty"`

	// (Attributes) GCP service account for GCP Kubernetes Engine (GKE). (see below for nested schema)
	GkeServiceAccount *GkeServiceAccountInitParameters `json:"gkeServiceAccount,omitempty" tf:"gke_service_account,omitempty"`

	// (String) NAT subnet name if GCP Private Service Connect is enabled.
	// NAT subnet name if GCP Private Service Connect is enabled.
	PscNATSubnetName *string `json:"pscNatSubnetName,omitempty" tf:"psc_nat_subnet_name,omitempty"`

	// (Attributes) GCP service account for the Redpanda cluster. (see below for nested schema)
	RedpandaClusterServiceAccount *RedpandaClusterServiceAccountInitParameters `json:"redpandaClusterServiceAccount,omitempty" tf:"redpanda_cluster_service_account,omitempty"`

	// (Attributes) GCP subnet where Redpanda cluster is deployed. (see below for nested schema)
	Subnet *SubnetInitParameters `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// (Attributes) GCP storage bucket for Tiered storage. (see below for nested schema)
	TieredStorageBucket *TieredStorageBucketInitParameters `json:"tieredStorageBucket,omitempty" tf:"tiered_storage_bucket,omitempty"`
}

type GCPObservation struct {

	// (Attributes) GCP service account for the agent. (see below for nested schema)
	AgentServiceAccount *AgentServiceAccountObservation `json:"agentServiceAccount,omitempty" tf:"agent_service_account,omitempty"`

	// (Attributes) GCP service account for managed connectors. (see below for nested schema)
	ConnectorServiceAccount *ConnectorServiceAccountObservation `json:"connectorServiceAccount,omitempty" tf:"connector_service_account,omitempty"`

	// (Attributes) GCP service account for Redpanda Console. (see below for nested schema)
	ConsoleServiceAccount *ConsoleServiceAccountObservation `json:"consoleServiceAccount,omitempty" tf:"console_service_account,omitempty"`

	// (Attributes) GCP service account for GCP Kubernetes Engine (GKE). (see below for nested schema)
	GkeServiceAccount *GkeServiceAccountObservation `json:"gkeServiceAccount,omitempty" tf:"gke_service_account,omitempty"`

	// (String) NAT subnet name if GCP Private Service Connect is enabled.
	// NAT subnet name if GCP Private Service Connect is enabled.
	PscNATSubnetName *string `json:"pscNatSubnetName,omitempty" tf:"psc_nat_subnet_name,omitempty"`

	// (Attributes) GCP service account for the Redpanda cluster. (see below for nested schema)
	RedpandaClusterServiceAccount *RedpandaClusterServiceAccountObservation `json:"redpandaClusterServiceAccount,omitempty" tf:"redpanda_cluster_service_account,omitempty"`

	// (Attributes) GCP subnet where Redpanda cluster is deployed. (see below for nested schema)
	Subnet *SubnetObservation `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// (Attributes) GCP storage bucket for Tiered storage. (see below for nested schema)
	TieredStorageBucket *TieredStorageBucketObservation `json:"tieredStorageBucket,omitempty" tf:"tiered_storage_bucket,omitempty"`
}

type GCPParameters struct {

	// (Attributes) GCP service account for the agent. (see below for nested schema)
	// +kubebuilder:validation:Optional
	AgentServiceAccount *AgentServiceAccountParameters `json:"agentServiceAccount" tf:"agent_service_account,omitempty"`

	// (Attributes) GCP service account for managed connectors. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ConnectorServiceAccount *ConnectorServiceAccountParameters `json:"connectorServiceAccount" tf:"connector_service_account,omitempty"`

	// (Attributes) GCP service account for Redpanda Console. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ConsoleServiceAccount *ConsoleServiceAccountParameters `json:"consoleServiceAccount" tf:"console_service_account,omitempty"`

	// (Attributes) GCP service account for GCP Kubernetes Engine (GKE). (see below for nested schema)
	// +kubebuilder:validation:Optional
	GkeServiceAccount *GkeServiceAccountParameters `json:"gkeServiceAccount" tf:"gke_service_account,omitempty"`

	// (String) NAT subnet name if GCP Private Service Connect is enabled.
	// NAT subnet name if GCP Private Service Connect is enabled.
	// +kubebuilder:validation:Optional
	PscNATSubnetName *string `json:"pscNatSubnetName,omitempty" tf:"psc_nat_subnet_name,omitempty"`

	// (Attributes) GCP service account for the Redpanda cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	RedpandaClusterServiceAccount *RedpandaClusterServiceAccountParameters `json:"redpandaClusterServiceAccount" tf:"redpanda_cluster_service_account,omitempty"`

	// (Attributes) GCP subnet where Redpanda cluster is deployed. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Subnet *SubnetParameters `json:"subnet" tf:"subnet,omitempty"`

	// (Attributes) GCP storage bucket for Tiered storage. (see below for nested schema)
	// +kubebuilder:validation:Optional
	TieredStorageBucket *TieredStorageBucketParameters `json:"tieredStorageBucket" tf:"tiered_storage_bucket,omitempty"`
}

type GCPPrivateServiceConnectInitParameters struct {

	// (Attributes List) List of consumers that are allowed to connect to Redpanda GCP PSC (Private Service Connect) service attachment. (see below for nested schema)
	ConsumerAcceptList []ConsumerAcceptListInitParameters `json:"consumerAcceptList,omitempty" tf:"consumer_accept_list,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether Redpanda GCP Private Service Connect is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether global access is enabled.
	// Whether global access is enabled.
	GlobalAccessEnabled *bool `json:"globalAccessEnabled,omitempty" tf:"global_access_enabled,omitempty"`
}

type GCPPrivateServiceConnectObservation struct {

	// (Attributes List) List of consumers that are allowed to connect to Redpanda GCP PSC (Private Service Connect) service attachment. (see below for nested schema)
	ConsumerAcceptList []ConsumerAcceptListObservation `json:"consumerAcceptList,omitempty" tf:"consumer_accept_list,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether Redpanda GCP Private Service Connect is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether global access is enabled.
	// Whether global access is enabled.
	GlobalAccessEnabled *bool `json:"globalAccessEnabled,omitempty" tf:"global_access_enabled,omitempty"`

	// (Attributes) Current status of the PrivateLink configuration. (see below for nested schema)
	Status *GCPPrivateServiceConnectStatusObservation `json:"status,omitempty" tf:"status,omitempty"`
}

type GCPPrivateServiceConnectParameters struct {

	// (Attributes List) List of consumers that are allowed to connect to Redpanda GCP PSC (Private Service Connect) service attachment. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ConsumerAcceptList []ConsumerAcceptListParameters `json:"consumerAcceptList" tf:"consumer_accept_list,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether Redpanda GCP Private Service Connect is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// (Boolean) Whether global access is enabled.
	// Whether global access is enabled.
	// +kubebuilder:validation:Optional
	GlobalAccessEnabled *bool `json:"globalAccessEnabled" tf:"global_access_enabled,omitempty"`
}

type GCPPrivateServiceConnectStatusInitParameters struct {
}

type GCPPrivateServiceConnectStatusObservation struct {

	// (Attributes List) List of connected endpoints. (see below for nested schema)
	ConnectedEndpoints []ConnectedEndpointsObservation `json:"connectedEndpoints,omitempty" tf:"connected_endpoints,omitempty"`

	// (String) Timestamp when the cluster was created.
	// When the Private Service Connect service was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (List of String) DNS A records for the service.
	// DNS A records for the service.
	DNSARecords []*string `json:"dnsARecords,omitempty" tf:"dns_a_records,omitempty"`

	// (String) When the PrivateLink service was deleted.
	// When the Private Service Connect service was deleted.
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// (Number) Base port for Kafka API nodes.
	// Base port for Kafka API nodes.
	KafkaAPINodeBasePort *float64 `json:"kafkaApiNodeBasePort,omitempty" tf:"kafka_api_node_base_port,omitempty"`

	// (Number) Port for Kafka API seed brokers.
	// Port for Kafka API seed brokers.
	KafkaAPISeedPort *float64 `json:"kafkaApiSeedPort,omitempty" tf:"kafka_api_seed_port,omitempty"`

	// (Number) Base port for HTTP proxy nodes.
	// Base port for HTTP proxy nodes.
	RedpandaProxyNodeBasePort *float64 `json:"redpandaProxyNodeBasePort,omitempty" tf:"redpanda_proxy_node_base_port,omitempty"`

	// (Number) Port for HTTP proxy.
	// Port for HTTP proxy.
	RedpandaProxySeedPort *float64 `json:"redpandaProxySeedPort,omitempty" tf:"redpanda_proxy_seed_port,omitempty"`

	// (Number) Port for Schema Registry.
	// Port for Schema Registry.
	SchemaRegistrySeedPort *float64 `json:"schemaRegistrySeedPort,omitempty" tf:"schema_registry_seed_port,omitempty"`

	// (String) Hostname for the seed brokers.
	// Hostname for the seed brokers.
	SeedHostname *string `json:"seedHostname,omitempty" tf:"seed_hostname,omitempty"`

	// (String) The service attachment identifier.
	// The service attachment identifier.
	ServiceAttachment *string `json:"serviceAttachment,omitempty" tf:"service_attachment,omitempty"`
}

type GCPPrivateServiceConnectStatusParameters struct {
}

type GkeServiceAccountInitParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type GkeServiceAccountObservation struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type GkeServiceAccountParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type HTTPProxyInitParameters struct {

	// (Attributes) mTLS configuration. (see below for nested schema)
	Mtls *MtlsInitParameters `json:"mtls,omitempty" tf:"mtls,omitempty"`
}

type HTTPProxyObservation struct {

	// (Attributes) mTLS configuration. (see below for nested schema)
	Mtls *MtlsObservation `json:"mtls,omitempty" tf:"mtls,omitempty"`

	// (String) The HTTP Proxy URL.
	// The HTTP Proxy URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type HTTPProxyParameters struct {

	// (Attributes) mTLS configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Mtls *MtlsParameters `json:"mtls,omitempty" tf:"mtls,omitempty"`
}

type K8SClusterRoleInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the Kubernetes cluster role
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type K8SClusterRoleObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the Kubernetes cluster role
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type K8SClusterRoleParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the Kubernetes cluster role
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type KafkaAPIInitParameters struct {

	// (Attributes) mTLS configuration. (see below for nested schema)
	Mtls *KafkaAPIMtlsInitParameters `json:"mtls,omitempty" tf:"mtls,omitempty"`
}

type KafkaAPIMtlsInitParameters struct {

	// (List of String) CA certificate in PEM format.
	// CA certificate in PEM format.
	CACertificatesPem []*string `json:"caCertificatesPem,omitempty" tf:"ca_certificates_pem,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether mTLS is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	PrincipalMappingRules []*string `json:"principalMappingRules,omitempty" tf:"principal_mapping_rules,omitempty"`
}

type KafkaAPIMtlsObservation struct {

	// (List of String) CA certificate in PEM format.
	// CA certificate in PEM format.
	CACertificatesPem []*string `json:"caCertificatesPem,omitempty" tf:"ca_certificates_pem,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether mTLS is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	PrincipalMappingRules []*string `json:"principalMappingRules,omitempty" tf:"principal_mapping_rules,omitempty"`
}

type KafkaAPIMtlsParameters struct {

	// (List of String) CA certificate in PEM format.
	// CA certificate in PEM format.
	// +kubebuilder:validation:Optional
	CACertificatesPem []*string `json:"caCertificatesPem,omitempty" tf:"ca_certificates_pem,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether mTLS is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// +kubebuilder:validation:Optional
	PrincipalMappingRules []*string `json:"principalMappingRules,omitempty" tf:"principal_mapping_rules,omitempty"`
}

type KafkaAPIObservation struct {

	// (Attributes) mTLS configuration. (see below for nested schema)
	Mtls *KafkaAPIMtlsObservation `json:"mtls,omitempty" tf:"mtls,omitempty"`

	// (List of String) List of Kafka broker addresses.
	// List of Kafka broker addresses.
	SeedBrokers []*string `json:"seedBrokers,omitempty" tf:"seed_brokers,omitempty"`
}

type KafkaAPIParameters struct {

	// (Attributes) mTLS configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Mtls *KafkaAPIMtlsParameters `json:"mtls,omitempty" tf:"mtls,omitempty"`
}

type KafkaConnectInitParameters struct {

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether Kafka Connect is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type KafkaConnectObservation struct {

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether Kafka Connect is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type KafkaConnectParameters struct {

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether Kafka Connect is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type MaintenanceWindowConfigInitParameters struct {

	// (Boolean) If true, maintenance can occur at any time.
	// If true, maintenance can occur at any time.
	Anytime *bool `json:"anytime,omitempty" tf:"anytime,omitempty"`

	// (Attributes) (see below for nested schema)
	DayHour *DayHourInitParameters `json:"dayHour,omitempty" tf:"day_hour,omitempty"`
}

type MaintenanceWindowConfigObservation struct {

	// (Boolean) If true, maintenance can occur at any time.
	// If true, maintenance can occur at any time.
	Anytime *bool `json:"anytime,omitempty" tf:"anytime,omitempty"`

	// (Attributes) (see below for nested schema)
	DayHour *DayHourObservation `json:"dayHour,omitempty" tf:"day_hour,omitempty"`

	// (Boolean) If true, maintenance window is unspecified.
	// If true, maintenance window is unspecified.
	Unspecified *bool `json:"unspecified,omitempty" tf:"unspecified,omitempty"`
}

type MaintenanceWindowConfigParameters struct {

	// (Boolean) If true, maintenance can occur at any time.
	// If true, maintenance can occur at any time.
	// +kubebuilder:validation:Optional
	Anytime *bool `json:"anytime,omitempty" tf:"anytime,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	DayHour *DayHourParameters `json:"dayHour,omitempty" tf:"day_hour,omitempty"`
}

type MtlsInitParameters struct {

	// (List of String) CA certificate in PEM format.
	// CA certificate in PEM format.
	CACertificatesPem []*string `json:"caCertificatesPem,omitempty" tf:"ca_certificates_pem,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether mTLS is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	PrincipalMappingRules []*string `json:"principalMappingRules,omitempty" tf:"principal_mapping_rules,omitempty"`
}

type MtlsObservation struct {

	// (List of String) CA certificate in PEM format.
	// CA certificate in PEM format.
	CACertificatesPem []*string `json:"caCertificatesPem,omitempty" tf:"ca_certificates_pem,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether mTLS is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	PrincipalMappingRules []*string `json:"principalMappingRules,omitempty" tf:"principal_mapping_rules,omitempty"`
}

type MtlsParameters struct {

	// (List of String) CA certificate in PEM format.
	// CA certificate in PEM format.
	// +kubebuilder:validation:Optional
	CACertificatesPem []*string `json:"caCertificatesPem,omitempty" tf:"ca_certificates_pem,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether mTLS is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// +kubebuilder:validation:Optional
	PrincipalMappingRules []*string `json:"principalMappingRules,omitempty" tf:"principal_mapping_rules,omitempty"`
}

type NodeSecurityGroupInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the node security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type NodeSecurityGroupObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the node security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type NodeSecurityGroupParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the node security group
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type PermissionsBoundaryPolicyInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the permissions boundary policy
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type PermissionsBoundaryPolicyObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the permissions boundary policy
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type PermissionsBoundaryPolicyParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the permissions boundary policy
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type PrivateEndpointConnectionsInitParameters struct {
}

type PrivateEndpointConnectionsObservation struct {

	// (String) The connection ID.
	// ID of the connection.
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// (String) Name of the connection.
	// Name of the connection.
	ConnectionName *string `json:"connectionName,omitempty" tf:"connection_name,omitempty"`

	// (String) Timestamp when the cluster was created.
	// When the endpoint connection was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) ID of the private endpoint.
	// ID of the private endpoint.
	PrivateEndpointID *string `json:"privateEndpointId,omitempty" tf:"private_endpoint_id,omitempty"`

	// (String) Name of the private endpoint.
	// Name of the private endpoint.
	PrivateEndpointName *string `json:"privateEndpointName,omitempty" tf:"private_endpoint_name,omitempty"`

	// (Attributes) Current status of the PrivateLink configuration. (see below for nested schema)
	// Status of the endpoint connection.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type PrivateEndpointConnectionsParameters struct {
}

type PrometheusInitParameters struct {
}

type PrometheusObservation struct {

	// (String) The HTTP Proxy URL.
	// The Prometheus metrics endpoint URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type PrometheusParameters struct {
}

type RedpandaAgentSecurityGroupInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the redpanda agent security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type RedpandaAgentSecurityGroupObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the redpanda agent security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type RedpandaAgentSecurityGroupParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the redpanda agent security group
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type RedpandaClusterServiceAccountInitParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type RedpandaClusterServiceAccountObservation struct {

	// (String) GCP service account email.
	// GCP service account email.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type RedpandaClusterServiceAccountParameters struct {

	// (String) GCP service account email.
	// GCP service account email.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type RedpandaConsoleInitParameters struct {
}

type RedpandaConsoleObservation struct {

	// (String) The HTTP Proxy URL.
	// The Redpanda Console URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RedpandaConsoleParameters struct {
}

type RedpandaNodeGroupInstanceProfileInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the redpanda node group instance profile
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type RedpandaNodeGroupInstanceProfileObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the redpanda node group instance profile
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type RedpandaNodeGroupInstanceProfileParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the redpanda node group instance profile
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type RedpandaNodeGroupSecurityGroupInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the redpanda node group security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type RedpandaNodeGroupSecurityGroupObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the redpanda node group security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type RedpandaNodeGroupSecurityGroupParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the redpanda node group security group
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type SchemaRegistryInitParameters struct {

	// (Attributes) mTLS configuration. (see below for nested schema)
	Mtls *SchemaRegistryMtlsInitParameters `json:"mtls,omitempty" tf:"mtls,omitempty"`
}

type SchemaRegistryMtlsInitParameters struct {

	// (List of String) CA certificate in PEM format.
	// CA certificate in PEM format.
	CACertificatesPem []*string `json:"caCertificatesPem,omitempty" tf:"ca_certificates_pem,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether mTLS is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	PrincipalMappingRules []*string `json:"principalMappingRules,omitempty" tf:"principal_mapping_rules,omitempty"`
}

type SchemaRegistryMtlsObservation struct {

	// (List of String) CA certificate in PEM format.
	// CA certificate in PEM format.
	CACertificatesPem []*string `json:"caCertificatesPem,omitempty" tf:"ca_certificates_pem,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether mTLS is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	PrincipalMappingRules []*string `json:"principalMappingRules,omitempty" tf:"principal_mapping_rules,omitempty"`
}

type SchemaRegistryMtlsParameters struct {

	// (List of String) CA certificate in PEM format.
	// CA certificate in PEM format.
	// +kubebuilder:validation:Optional
	CACertificatesPem []*string `json:"caCertificatesPem,omitempty" tf:"ca_certificates_pem,omitempty"`

	// (Boolean) Whether AWS PrivateLink is enabled.
	// Whether mTLS is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (List of String) Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// Principal mapping rules for mTLS authentication. See the Redpanda documentation on configuring authentication.
	// +kubebuilder:validation:Optional
	PrincipalMappingRules []*string `json:"principalMappingRules,omitempty" tf:"principal_mapping_rules,omitempty"`
}

type SchemaRegistryObservation struct {

	// (Attributes) mTLS configuration. (see below for nested schema)
	Mtls *SchemaRegistryMtlsObservation `json:"mtls,omitempty" tf:"mtls,omitempty"`

	// (String) The HTTP Proxy URL.
	// The Schema Registry URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type SchemaRegistryParameters struct {

	// (Attributes) mTLS configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Mtls *SchemaRegistryMtlsParameters `json:"mtls,omitempty" tf:"mtls,omitempty"`
}

type SecondaryIPv4RangePodsInitParameters struct {

	// (String) Unique name of the cluster.
	// Secondary IPv4 range name for pods.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SecondaryIPv4RangePodsObservation struct {

	// (String) Unique name of the cluster.
	// Secondary IPv4 range name for pods.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SecondaryIPv4RangePodsParameters struct {

	// (String) Unique name of the cluster.
	// Secondary IPv4 range name for pods.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type SecondaryIPv4RangeServicesInitParameters struct {

	// (String) Unique name of the cluster.
	// Secondary IPv4 range name for services.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SecondaryIPv4RangeServicesObservation struct {

	// (String) Unique name of the cluster.
	// Secondary IPv4 range name for services.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SecondaryIPv4RangeServicesParameters struct {

	// (String) Unique name of the cluster.
	// Secondary IPv4 range name for services.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type StateDescriptionInitParameters struct {
}

type StateDescriptionObservation struct {

	// (Number) Error code if cluster is in error state.
	// Error code if cluster is in error state.
	Code *float64 `json:"code,omitempty" tf:"code,omitempty"`

	// (String) Detailed error message if cluster is in error state.
	// Detailed error message if cluster is in error state.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`
}

type StateDescriptionParameters struct {
}

type StatusInitParameters struct {
}

type StatusObservation struct {

	// (Number) Port for Redpanda Console.
	// Port for Redpanda Console.
	ConsolePort *float64 `json:"consolePort,omitempty" tf:"console_port,omitempty"`

	// (String) Timestamp when the cluster was created.
	// When the PrivateLink service was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) When the PrivateLink service was deleted.
	// When the PrivateLink service was deleted.
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// (Number) Base port for Kafka API nodes.
	// Base port for Kafka API nodes.
	KafkaAPINodeBasePort *float64 `json:"kafkaApiNodeBasePort,omitempty" tf:"kafka_api_node_base_port,omitempty"`

	// (Number) Port for Kafka API seed brokers.
	// Port for Kafka API seed brokers.
	KafkaAPISeedPort *float64 `json:"kafkaApiSeedPort,omitempty" tf:"kafka_api_seed_port,omitempty"`

	// (Number) Base port for HTTP proxy nodes.
	// Base port for HTTP proxy nodes.
	RedpandaProxyNodeBasePort *float64 `json:"redpandaProxyNodeBasePort,omitempty" tf:"redpanda_proxy_node_base_port,omitempty"`

	// (Number) Port for HTTP proxy.
	// Port for HTTP proxy.
	RedpandaProxySeedPort *float64 `json:"redpandaProxySeedPort,omitempty" tf:"redpanda_proxy_seed_port,omitempty"`

	// (Number) Port for Schema Registry.
	// Port for Schema Registry.
	SchemaRegistrySeedPort *float64 `json:"schemaRegistrySeedPort,omitempty" tf:"schema_registry_seed_port,omitempty"`

	// (String) The PrivateLink service ID.
	// The PrivateLink service ID.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) The PrivateLink service name.
	// The PrivateLink service name.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// (String) Current state of the PrivateLink service.
	// Current state of the PrivateLink service.
	ServiceState *string `json:"serviceState,omitempty" tf:"service_state,omitempty"`

	// (Attributes List) List of VPC endpoint connections. (see below for nested schema)
	VPCEndpointConnections []VPCEndpointConnectionsObservation `json:"vpcEndpointConnections,omitempty" tf:"vpc_endpoint_connections,omitempty"`
}

type StatusParameters struct {
}

type SubnetInitParameters struct {

	// (String) Kubernetes Master IPv4 range, e.g. 10.0.0.0/24.
	// Kubernetes Master IPv4 range, e.g. 10.0.0.0/24.
	K8SMasterIPv4Range *string `json:"k8sMasterIpv4Range,omitempty" tf:"k8s_master_ipv4_range,omitempty"`

	// (String) Unique name of the cluster.
	// Subnet name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Secondary IPv4 range for pods. (see below for nested schema)
	SecondaryIPv4RangePods *SecondaryIPv4RangePodsInitParameters `json:"secondaryIpv4RangePods,omitempty" tf:"secondary_ipv4_range_pods,omitempty"`

	// (Attributes) Secondary IPv4 range for services. (see below for nested schema)
	SecondaryIPv4RangeServices *SecondaryIPv4RangeServicesInitParameters `json:"secondaryIpv4RangeServices,omitempty" tf:"secondary_ipv4_range_services,omitempty"`
}

type SubnetObservation struct {

	// (String) Kubernetes Master IPv4 range, e.g. 10.0.0.0/24.
	// Kubernetes Master IPv4 range, e.g. 10.0.0.0/24.
	K8SMasterIPv4Range *string `json:"k8sMasterIpv4Range,omitempty" tf:"k8s_master_ipv4_range,omitempty"`

	// (String) Unique name of the cluster.
	// Subnet name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Secondary IPv4 range for pods. (see below for nested schema)
	SecondaryIPv4RangePods *SecondaryIPv4RangePodsObservation `json:"secondaryIpv4RangePods,omitempty" tf:"secondary_ipv4_range_pods,omitempty"`

	// (Attributes) Secondary IPv4 range for services. (see below for nested schema)
	SecondaryIPv4RangeServices *SecondaryIPv4RangeServicesObservation `json:"secondaryIpv4RangeServices,omitempty" tf:"secondary_ipv4_range_services,omitempty"`
}

type SubnetParameters struct {

	// (String) Kubernetes Master IPv4 range, e.g. 10.0.0.0/24.
	// Kubernetes Master IPv4 range, e.g. 10.0.0.0/24.
	// +kubebuilder:validation:Optional
	K8SMasterIPv4Range *string `json:"k8sMasterIpv4Range" tf:"k8s_master_ipv4_range,omitempty"`

	// (String) Unique name of the cluster.
	// Subnet name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (Attributes) Secondary IPv4 range for pods. (see below for nested schema)
	// +kubebuilder:validation:Optional
	SecondaryIPv4RangePods *SecondaryIPv4RangePodsParameters `json:"secondaryIpv4RangePods" tf:"secondary_ipv4_range_pods,omitempty"`

	// (Attributes) Secondary IPv4 range for services. (see below for nested schema)
	// +kubebuilder:validation:Optional
	SecondaryIPv4RangeServices *SecondaryIPv4RangeServicesParameters `json:"secondaryIpv4RangeServices" tf:"secondary_ipv4_range_services,omitempty"`
}

type TieredStorageBucketInitParameters struct {

	// (String) Unique name of the cluster.
	// GCP storage bucket name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TieredStorageBucketObservation struct {

	// (String) Unique name of the cluster.
	// GCP storage bucket name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TieredStorageBucketParameters struct {

	// (String) Unique name of the cluster.
	// GCP storage bucket name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type TimeoutsInitParameters struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsObservation struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsParameters struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type UtilityNodeGroupInstanceProfileInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the utility node group instance profile
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type UtilityNodeGroupInstanceProfileObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the utility node group instance profile
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type UtilityNodeGroupInstanceProfileParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the utility node group instance profile
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type UtilitySecurityGroupInitParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the utility security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type UtilitySecurityGroupObservation struct {

	// (String) ARN for the agent instance profile
	// ARN for the utility security group
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type UtilitySecurityGroupParameters struct {

	// (String) ARN for the agent instance profile
	// ARN for the utility security group
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type VPCEndpointConnectionsInitParameters struct {
}

type VPCEndpointConnectionsObservation struct {

	// (String) The connection ID.
	// The connection ID.
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// (String) Timestamp when the cluster was created.
	// When the endpoint connection was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Attributes List) DNS entries for the endpoint. (see below for nested schema)
	DNSEntries []DNSEntriesObservation `json:"dnsEntries,omitempty" tf:"dns_entries,omitempty"`

	// (String) ID of the cluster. ID is an output from the Create Cluster endpoint and cannot be set by the caller.
	// The endpoint connection ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of String) ARNs of associated load balancers.
	// ARNs of associated load balancers.
	LoadBalancerArns []*string `json:"loadBalancerArns,omitempty" tf:"load_balancer_arns,omitempty"`

	// (String) Owner of the endpoint connection.
	// Owner of the endpoint connection.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String) Current state of the cluster.
	// State of the endpoint connection.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type VPCEndpointConnectionsParameters struct {
}

// ClusterSpec defines the desired state of Cluster
type ClusterSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClusterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterInitParameters `json:"initProvider,omitempty"`
}

// ClusterStatus defines the observed state of Cluster.
type ClusterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cluster is the Schema for the Clusters API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,redpanda}
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudProvider) || (has(self.initProvider) && has(self.initProvider.cloudProvider))",message="spec.forProvider.cloudProvider is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterType) || (has(self.initProvider) && has(self.initProvider.clusterType))",message="spec.forProvider.clusterType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.connectionType) || (has(self.initProvider) && has(self.initProvider.connectionType))",message="spec.forProvider.connectionType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkId) || (has(self.initProvider) && has(self.initProvider.networkId))",message="spec.forProvider.networkId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resourceGroupId) || (has(self.initProvider) && has(self.initProvider.resourceGroupId))",message="spec.forProvider.resourceGroupId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.throughputTier) || (has(self.initProvider) && has(self.initProvider.throughputTier))",message="spec.forProvider.throughputTier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zones) || (has(self.initProvider) && has(self.initProvider.zones))",message="spec.forProvider.zones is a required parameter"
	Spec   ClusterSpec   `json:"spec"`
	Status ClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterList contains a list of Clusters
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

// Repository type metadata.
var (
	Cluster_Kind             = "Cluster"
	Cluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cluster_Kind}.String()
	Cluster_KindAPIVersion   = Cluster_Kind + "." + CRDGroupVersion.String()
	Cluster_GroupVersionKind = CRDGroupVersion.WithKind(Cluster_Kind)
)

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
