// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CustomerManagedResourcesAwsInitParameters struct {

	// (Attributes) (see below for nested schema)
	DynamodbTable *DynamodbTableInitParameters `json:"dynamodbTable,omitempty" tf:"dynamodb_table,omitempty"`

	// (Attributes) (see below for nested schema)
	ManagementBucket *ManagementBucketInitParameters `json:"managementBucket,omitempty" tf:"management_bucket,omitempty"`

	// (Attributes) (see below for nested schema)
	PrivateSubnets *PrivateSubnetsInitParameters `json:"privateSubnets,omitempty" tf:"private_subnets,omitempty"`

	// (Attributes) (see below for nested schema)
	VPC *VPCInitParameters `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type CustomerManagedResourcesAwsObservation struct {

	// (Attributes) (see below for nested schema)
	DynamodbTable *DynamodbTableObservation `json:"dynamodbTable,omitempty" tf:"dynamodb_table,omitempty"`

	// (Attributes) (see below for nested schema)
	ManagementBucket *ManagementBucketObservation `json:"managementBucket,omitempty" tf:"management_bucket,omitempty"`

	// (Attributes) (see below for nested schema)
	PrivateSubnets *PrivateSubnetsObservation `json:"privateSubnets,omitempty" tf:"private_subnets,omitempty"`

	// (Attributes) (see below for nested schema)
	VPC *VPCObservation `json:"vpc,omitempty" tf:"vpc,omitempty"`
}

type CustomerManagedResourcesAwsParameters struct {

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	DynamodbTable *DynamodbTableParameters `json:"dynamodbTable" tf:"dynamodb_table,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	ManagementBucket *ManagementBucketParameters `json:"managementBucket" tf:"management_bucket,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	PrivateSubnets *PrivateSubnetsParameters `json:"privateSubnets" tf:"private_subnets,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	VPC *VPCParameters `json:"vpc" tf:"vpc,omitempty"`
}

type CustomerManagedResourcesGCPInitParameters struct {

	// (Attributes) (see below for nested schema)
	ManagementBucket *GCPManagementBucketInitParameters `json:"managementBucket,omitempty" tf:"management_bucket,omitempty"`

	// created network where the Redpanda cluster is deployed
	// Name of user-created network where the Redpanda cluster is deployed
	NetworkName *string `json:"networkName,omitempty" tf:"network_name,omitempty"`

	// (String) GCP project ID where the network is created
	// GCP project ID where the network is created
	NetworkProjectID *string `json:"networkProjectId,omitempty" tf:"network_project_id,omitempty"`
}

type CustomerManagedResourcesGCPObservation struct {

	// (Attributes) (see below for nested schema)
	ManagementBucket *GCPManagementBucketObservation `json:"managementBucket,omitempty" tf:"management_bucket,omitempty"`

	// created network where the Redpanda cluster is deployed
	// Name of user-created network where the Redpanda cluster is deployed
	NetworkName *string `json:"networkName,omitempty" tf:"network_name,omitempty"`

	// (String) GCP project ID where the network is created
	// GCP project ID where the network is created
	NetworkProjectID *string `json:"networkProjectId,omitempty" tf:"network_project_id,omitempty"`
}

type CustomerManagedResourcesGCPParameters struct {

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	ManagementBucket *GCPManagementBucketParameters `json:"managementBucket" tf:"management_bucket,omitempty"`

	// created network where the Redpanda cluster is deployed
	// Name of user-created network where the Redpanda cluster is deployed
	// +kubebuilder:validation:Optional
	NetworkName *string `json:"networkName" tf:"network_name,omitempty"`

	// (String) GCP project ID where the network is created
	// GCP project ID where the network is created
	// +kubebuilder:validation:Optional
	NetworkProjectID *string `json:"networkProjectId" tf:"network_project_id,omitempty"`
}

type DynamodbTableInitParameters struct {

	// (String) AWS DynamoDB table identifier
	// AWS DynamoDB table identifier
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type DynamodbTableObservation struct {

	// (String) AWS DynamoDB table identifier
	// AWS DynamoDB table identifier
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type DynamodbTableParameters struct {

	// (String) AWS DynamoDB table identifier
	// AWS DynamoDB table identifier
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type GCPManagementBucketInitParameters struct {

	// (String) Name of the network
	// GCP storage bucket name for storing the state of Redpanda cluster deployment
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type GCPManagementBucketObservation struct {

	// (String) Name of the network
	// GCP storage bucket name for storing the state of Redpanda cluster deployment
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type GCPManagementBucketParameters struct {

	// (String) Name of the network
	// GCP storage bucket name for storing the state of Redpanda cluster deployment
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type ManagementBucketInitParameters struct {

	// (String) AWS DynamoDB table identifier
	// AWS storage bucket identifier
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type ManagementBucketObservation struct {

	// (String) AWS DynamoDB table identifier
	// AWS storage bucket identifier
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type ManagementBucketParameters struct {

	// (String) AWS DynamoDB table identifier
	// AWS storage bucket identifier
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

type NetworkCustomerManagedResourcesInitParameters struct {

	// (Attributes) (see below for nested schema)
	Aws *CustomerManagedResourcesAwsInitParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// (Attributes) (see below for nested schema)
	GCP *CustomerManagedResourcesGCPInitParameters `json:"gcp,omitempty" tf:"gcp,omitempty"`
}

type NetworkCustomerManagedResourcesObservation struct {

	// (Attributes) (see below for nested schema)
	Aws *CustomerManagedResourcesAwsObservation `json:"aws,omitempty" tf:"aws,omitempty"`

	// (Attributes) (see below for nested schema)
	GCP *CustomerManagedResourcesGCPObservation `json:"gcp,omitempty" tf:"gcp,omitempty"`
}

type NetworkCustomerManagedResourcesParameters struct {

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Aws *CustomerManagedResourcesAwsParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	GCP *CustomerManagedResourcesGCPParameters `json:"gcp,omitempty" tf:"gcp,omitempty"`
}

type NetworkInitParameters struct {

	// (String) The cidr_block to create the network in
	// The cidr_block to create the network in
	CidrBlock *string `json:"cidrBlock,omitempty" tf:"cidr_block,omitempty"`

	// (String) The cloud provider to create the network in.
	// The cloud provider to create the network in.
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String) The type of cluster this network is associated with, can be one of dedicated or byoc
	// The type of cluster this network is associated with, can be one of dedicated or byoc
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// (Attributes) (see below for nested schema)
	CustomerManagedResources *NetworkCustomerManagedResourcesInitParameters `json:"customerManagedResources,omitempty" tf:"customer_managed_resources,omitempty"`

	// (String) Name of the network
	// Name of the network
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region to create the network in.
	// The region to create the network in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The ID of the resource group in which to create the network
	// The ID of the resource group in which to create the network
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/resource/v1alpha1.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Reference to a Group in resource to populate resourceGroupId.
	// +kubebuilder:validation:Optional
	ResourceGroupIDRef *v1.Reference `json:"resourceGroupIdRef,omitempty" tf:"-"`

	// Selector for a Group in resource to populate resourceGroupId.
	// +kubebuilder:validation:Optional
	ResourceGroupIDSelector *v1.Selector `json:"resourceGroupIdSelector,omitempty" tf:"-"`

	// (Attributes) (see below for nested schema)
	Timeouts *NetworkTimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type NetworkObservation struct {

	// (String) The cidr_block to create the network in
	// The cidr_block to create the network in
	CidrBlock *string `json:"cidrBlock,omitempty" tf:"cidr_block,omitempty"`

	// (String) The cloud provider to create the network in.
	// The cloud provider to create the network in.
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String) The type of cluster this network is associated with, can be one of dedicated or byoc
	// The type of cluster this network is associated with, can be one of dedicated or byoc
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// (Attributes) (see below for nested schema)
	CustomerManagedResources *NetworkCustomerManagedResourcesObservation `json:"customerManagedResources,omitempty" tf:"customer_managed_resources,omitempty"`

	// (String) The ID of the network
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the network
	// Name of the network
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region to create the network in.
	// The region to create the network in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The ID of the resource group in which to create the network
	// The ID of the resource group in which to create the network
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// (Attributes) (see below for nested schema)
	Timeouts *NetworkTimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type NetworkParameters struct {

	// (String) The cidr_block to create the network in
	// The cidr_block to create the network in
	// +kubebuilder:validation:Optional
	CidrBlock *string `json:"cidrBlock,omitempty" tf:"cidr_block,omitempty"`

	// (String) The cloud provider to create the network in.
	// The cloud provider to create the network in.
	// +kubebuilder:validation:Optional
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String) The type of cluster this network is associated with, can be one of dedicated or byoc
	// The type of cluster this network is associated with, can be one of dedicated or byoc
	// +kubebuilder:validation:Optional
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	CustomerManagedResources *NetworkCustomerManagedResourcesParameters `json:"customerManagedResources,omitempty" tf:"customer_managed_resources,omitempty"`

	// (String) Name of the network
	// Name of the network
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The region to create the network in.
	// The region to create the network in.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The ID of the resource group in which to create the network
	// The ID of the resource group in which to create the network
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/resource/v1alpha1.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Reference to a Group in resource to populate resourceGroupId.
	// +kubebuilder:validation:Optional
	ResourceGroupIDRef *v1.Reference `json:"resourceGroupIdRef,omitempty" tf:"-"`

	// Selector for a Group in resource to populate resourceGroupId.
	// +kubebuilder:validation:Optional
	ResourceGroupIDSelector *v1.Selector `json:"resourceGroupIdSelector,omitempty" tf:"-"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Timeouts *NetworkTimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type NetworkTimeoutsInitParameters struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`
}

type NetworkTimeoutsObservation struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`
}

type NetworkTimeoutsParameters struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`
}

type PrivateSubnetsInitParameters struct {

	// (List of String) AWS private subnet identifiers
	// AWS private subnet identifiers
	Arns []*string `json:"arns,omitempty" tf:"arns,omitempty"`
}

type PrivateSubnetsObservation struct {

	// (List of String) AWS private subnet identifiers
	// AWS private subnet identifiers
	Arns []*string `json:"arns,omitempty" tf:"arns,omitempty"`
}

type PrivateSubnetsParameters struct {

	// (List of String) AWS private subnet identifiers
	// AWS private subnet identifiers
	// +kubebuilder:validation:Optional
	Arns []*string `json:"arns" tf:"arns,omitempty"`
}

type VPCInitParameters struct {

	// (String) AWS DynamoDB table identifier
	// AWS VPC identifier
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type VPCObservation struct {

	// (String) AWS DynamoDB table identifier
	// AWS VPC identifier
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type VPCParameters struct {

	// (String) AWS DynamoDB table identifier
	// AWS VPC identifier
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn" tf:"arn,omitempty"`
}

// NetworkSpec defines the desired state of Network
type NetworkSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkInitParameters `json:"initProvider,omitempty"`
}

// NetworkStatus defines the observed state of Network.
type NetworkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Network is the Schema for the Networks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,redpanda}
type Network struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudProvider) || (has(self.initProvider) && has(self.initProvider.cloudProvider))",message="spec.forProvider.cloudProvider is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterType) || (has(self.initProvider) && has(self.initProvider.clusterType))",message="spec.forProvider.clusterType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   NetworkSpec   `json:"spec"`
	Status NetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkList contains a list of Networks
type NetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Network `json:"items"`
}

// Repository type metadata.
var (
	Network_Kind             = "Network"
	Network_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Network_Kind}.String()
	Network_KindAPIVersion   = Network_Kind + "." + CRDGroupVersion.String()
	Network_GroupVersionKind = CRDGroupVersion.WithKind(Network_Kind)
)

func init() {
	SchemeBuilder.Register(&Network{}, &NetworkList{})
}
