// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ReferencesInitParameters struct {

	// (String) The name of the referenced schema.
	// The name of the referenced schema.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The subject name for the schema.
	// The subject of the referenced schema.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (Number) The version of the schema.
	// The version of the referenced schema.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type ReferencesObservation struct {

	// (String) The name of the referenced schema.
	// The name of the referenced schema.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The subject name for the schema.
	// The subject of the referenced schema.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (Number) The version of the schema.
	// The version of the referenced schema.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type ReferencesParameters struct {

	// (String) The name of the referenced schema.
	// The name of the referenced schema.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) The subject name for the schema.
	// The subject of the referenced schema.
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`

	// (Number) The version of the schema.
	// The version of the referenced schema.
	// +kubebuilder:validation:Optional
	Version *float64 `json:"version" tf:"version,omitempty"`
}

type SchemaInitParameters struct {

	// (Boolean) When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	// When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// (String) The ID of the cluster where the schema is stored.
	// The ID of the cluster where the schema is stored.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/redpanda/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in redpanda to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in redpanda to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	// The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	Compatibility *string `json:"compatibility,omitempty" tf:"compatibility,omitempty"`

	// (String, Sensitive) The SASL password for Schema Registry authentication.
	// The SASL password for Schema Registry authentication.
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Attributes List) List of schema references. (see below for nested schema)
	References []ReferencesInitParameters `json:"references,omitempty" tf:"references,omitempty"`

	// (String) The schema definition in JSON format.
	// The schema definition in JSON format.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The type of schema (AVRO, JSON, PROTOBUF).
	// The type of schema (AVRO, JSON, PROTOBUF).
	SchemaType *string `json:"schemaType,omitempty" tf:"schema_type,omitempty"`

	// (String) The subject name for the schema.
	// The subject name for the schema.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (String) The SASL username for Schema Registry authentication.
	// The SASL username for Schema Registry authentication.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/redpanda/v1alpha1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// Reference to a User in redpanda to populate username.
	// +kubebuilder:validation:Optional
	UsernameRef *v1.Reference `json:"usernameRef,omitempty" tf:"-"`

	// Selector for a User in redpanda to populate username.
	// +kubebuilder:validation:Optional
	UsernameSelector *v1.Selector `json:"usernameSelector,omitempty" tf:"-"`
}

type SchemaObservation struct {

	// (Boolean) When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	// When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// (String) The ID of the cluster where the schema is stored.
	// The ID of the cluster where the schema is stored.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	// The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	Compatibility *string `json:"compatibility,omitempty" tf:"compatibility,omitempty"`

	// (Number) The unique identifier for the schema.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes List) List of schema references. (see below for nested schema)
	References []ReferencesObservation `json:"references,omitempty" tf:"references,omitempty"`

	// (String) The schema definition in JSON format.
	// The schema definition in JSON format.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The type of schema (AVRO, JSON, PROTOBUF).
	// The type of schema (AVRO, JSON, PROTOBUF).
	SchemaType *string `json:"schemaType,omitempty" tf:"schema_type,omitempty"`

	// (String) The subject name for the schema.
	// The subject name for the schema.
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (String) The SASL username for Schema Registry authentication.
	// The SASL username for Schema Registry authentication.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// (Number) The version of the schema.
	// The version of the schema.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type SchemaParameters struct {

	// (Boolean) When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	// When enabled, prevents the resource from being deleted if the cluster is unreachable. When disabled (default), the resource will be removed from state without attempting deletion when the cluster is unreachable.
	// +kubebuilder:validation:Optional
	AllowDeletion *bool `json:"allowDeletion,omitempty" tf:"allow_deletion,omitempty"`

	// (String) The ID of the cluster where the schema is stored.
	// The ID of the cluster where the schema is stored.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/redpanda/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in redpanda to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in redpanda to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	// The compatibility level for schema evolution (BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE). Defaults to BACKWARD.
	// +kubebuilder:validation:Optional
	Compatibility *string `json:"compatibility,omitempty" tf:"compatibility,omitempty"`

	// (String, Sensitive) The SASL password for Schema Registry authentication.
	// The SASL password for Schema Registry authentication.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (Attributes List) List of schema references. (see below for nested schema)
	// +kubebuilder:validation:Optional
	References []ReferencesParameters `json:"references,omitempty" tf:"references,omitempty"`

	// (String) The schema definition in JSON format.
	// The schema definition in JSON format.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) The type of schema (AVRO, JSON, PROTOBUF).
	// The type of schema (AVRO, JSON, PROTOBUF).
	// +kubebuilder:validation:Optional
	SchemaType *string `json:"schemaType,omitempty" tf:"schema_type,omitempty"`

	// (String) The subject name for the schema.
	// The subject name for the schema.
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// (String) The SASL username for Schema Registry authentication.
	// The SASL username for Schema Registry authentication.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/redpanda/v1alpha1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// Reference to a User in redpanda to populate username.
	// +kubebuilder:validation:Optional
	UsernameRef *v1.Reference `json:"usernameRef,omitempty" tf:"-"`

	// Selector for a User in redpanda to populate username.
	// +kubebuilder:validation:Optional
	UsernameSelector *v1.Selector `json:"usernameSelector,omitempty" tf:"-"`
}

// SchemaSpec defines the desired state of Schema
type SchemaSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SchemaParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SchemaInitParameters `json:"initProvider,omitempty"`
}

// SchemaStatus defines the observed state of Schema.
type SchemaStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SchemaObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Schema is the Schema for the Schemas API. Schema represents a Schema Registry schema
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,redpanda}
type Schema struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schema) || (has(self.initProvider) && has(self.initProvider.schema))",message="spec.forProvider.schema is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subject) || (has(self.initProvider) && has(self.initProvider.subject))",message="spec.forProvider.subject is a required parameter"
	Spec   SchemaSpec   `json:"spec"`
	Status SchemaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SchemaList contains a list of Schemas
type SchemaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Schema `json:"items"`
}

// Repository type metadata.
var (
	Schema_Kind             = "Schema"
	Schema_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Schema_Kind}.String()
	Schema_KindAPIVersion   = Schema_Kind + "." + CRDGroupVersion.String()
	Schema_GroupVersionKind = CRDGroupVersion.WithKind(Schema_Kind)
)

func init() {
	SchemeBuilder.Register(&Schema{}, &SchemaList{})
}
