// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-redpanda/apis/namespaced/resource/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ACL.
func (mg *ACL) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterAPIURL),
		Extract:      resource.ExtractParamPath("cluster_api_url", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ClusterAPIURLRef,
		Selector:     mg.Spec.ForProvider.ClusterAPIURLSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterAPIURL")
	}
	mg.Spec.ForProvider.ClusterAPIURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterAPIURLRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ResourceName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ResourceNameRef,
		Selector:     mg.Spec.ForProvider.ResourceNameSelector,
		To: reference.To{
			List:    &TopicList{},
			Managed: &Topic{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ResourceName")
	}
	mg.Spec.ForProvider.ResourceName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ResourceNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterAPIURL),
		Extract:      resource.ExtractParamPath("cluster_api_url", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ClusterAPIURLRef,
		Selector:     mg.Spec.InitProvider.ClusterAPIURLSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterAPIURL")
	}
	mg.Spec.InitProvider.ClusterAPIURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterAPIURLRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ResourceName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ResourceNameRef,
		Selector:     mg.Spec.InitProvider.ResourceNameSelector,
		To: reference.To{
			List:    &TopicList{},
			Managed: &Topic{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ResourceName")
	}
	mg.Spec.InitProvider.ResourceName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ResourceNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Cluster.
func (mg *Cluster) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CloudProvider),
		Extract:      resource.ExtractParamPath("cloud_provider", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CloudProviderRef,
		Selector:     mg.Spec.ForProvider.CloudProviderSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CloudProvider")
	}
	mg.Spec.ForProvider.CloudProvider = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CloudProviderRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterType),
		Extract:      resource.ExtractParamPath("cluster_type", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ClusterTypeRef,
		Selector:     mg.Spec.ForProvider.ClusterTypeSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterType")
	}
	mg.Spec.ForProvider.ClusterType = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterTypeRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkIDRef,
		Selector:     mg.Spec.ForProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkID")
	}
	mg.Spec.ForProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Region),
		Extract:      resource.ExtractParamPath("region", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.RegionRef,
		Selector:     mg.Spec.ForProvider.RegionSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Region")
	}
	mg.Spec.ForProvider.Region = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RegionRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ResourceGroupID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ResourceGroupIDRef,
		Selector:     mg.Spec.ForProvider.ResourceGroupIDSelector,
		To: reference.To{
			List:    &v1alpha1.GroupList{},
			Managed: &v1alpha1.Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ResourceGroupID")
	}
	mg.Spec.ForProvider.ResourceGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ResourceGroupIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CloudProvider),
		Extract:      resource.ExtractParamPath("cloud_provider", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CloudProviderRef,
		Selector:     mg.Spec.InitProvider.CloudProviderSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CloudProvider")
	}
	mg.Spec.InitProvider.CloudProvider = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CloudProviderRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterType),
		Extract:      resource.ExtractParamPath("cluster_type", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ClusterTypeRef,
		Selector:     mg.Spec.InitProvider.ClusterTypeSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterType")
	}
	mg.Spec.InitProvider.ClusterType = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterTypeRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkIDRef,
		Selector:     mg.Spec.InitProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkID")
	}
	mg.Spec.InitProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Region),
		Extract:      resource.ExtractParamPath("region", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.RegionRef,
		Selector:     mg.Spec.InitProvider.RegionSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Region")
	}
	mg.Spec.InitProvider.Region = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RegionRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ResourceGroupID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ResourceGroupIDRef,
		Selector:     mg.Spec.InitProvider.ResourceGroupIDSelector,
		To: reference.To{
			List:    &v1alpha1.GroupList{},
			Managed: &v1alpha1.Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ResourceGroupID")
	}
	mg.Spec.InitProvider.ResourceGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ResourceGroupIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Network.
func (mg *Network) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ResourceGroupID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ResourceGroupIDRef,
		Selector:     mg.Spec.ForProvider.ResourceGroupIDSelector,
		To: reference.To{
			List:    &v1alpha1.GroupList{},
			Managed: &v1alpha1.Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ResourceGroupID")
	}
	mg.Spec.ForProvider.ResourceGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ResourceGroupIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ResourceGroupID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ResourceGroupIDRef,
		Selector:     mg.Spec.InitProvider.ResourceGroupIDSelector,
		To: reference.To{
			List:    &v1alpha1.GroupList{},
			Managed: &v1alpha1.Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ResourceGroupID")
	}
	mg.Spec.InitProvider.ResourceGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ResourceGroupIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Schema.
func (mg *Schema) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ClusterIDRef,
		Selector:     mg.Spec.ForProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterID")
	}
	mg.Spec.ForProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Username),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.UsernameRef,
		Selector:     mg.Spec.ForProvider.UsernameSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Username")
	}
	mg.Spec.ForProvider.Username = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UsernameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ClusterIDRef,
		Selector:     mg.Spec.InitProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterID")
	}
	mg.Spec.InitProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Username),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.UsernameRef,
		Selector:     mg.Spec.InitProvider.UsernameSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Username")
	}
	mg.Spec.InitProvider.Username = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UsernameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Topic.
func (mg *Topic) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterAPIURL),
		Extract:      resource.ExtractParamPath("cluster_api_url", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ClusterAPIURLRef,
		Selector:     mg.Spec.ForProvider.ClusterAPIURLSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterAPIURL")
	}
	mg.Spec.ForProvider.ClusterAPIURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterAPIURLRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterAPIURL),
		Extract:      resource.ExtractParamPath("cluster_api_url", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ClusterAPIURLRef,
		Selector:     mg.Spec.InitProvider.ClusterAPIURLSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterAPIURL")
	}
	mg.Spec.InitProvider.ClusterAPIURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterAPIURLRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this User.
func (mg *User) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterAPIURL),
		Extract:      resource.ExtractParamPath("cluster_api_url", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ClusterAPIURLRef,
		Selector:     mg.Spec.ForProvider.ClusterAPIURLSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterAPIURL")
	}
	mg.Spec.ForProvider.ClusterAPIURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterAPIURLRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterAPIURL),
		Extract:      resource.ExtractParamPath("cluster_api_url", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ClusterAPIURLRef,
		Selector:     mg.Spec.InitProvider.ClusterAPIURLSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterAPIURL")
	}
	mg.Spec.InitProvider.ClusterAPIURL = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterAPIURLRef = rsp.ResolvedReference

	return nil
}
