apiVersion: schema.redpanda.crossplane.io/v1alpha1
kind: RegistryACL
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/registryacl
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterId: ${redpanda_cluster.example.id}
    host: '*'
    operation: READ
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    patternType: LITERAL
    permission: ALLOW
    principal: example-user
    resourceName: user-value
    resourceType: SUBJECT
    usernameSecretRef:
      key: attribute.name
      name: example-user
      namespace: upbound-system

---

apiVersion: redpanda.redpanda.crossplane.io/v1alpha1
kind: ACL
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/registryacl
  labels:
    testing.upbound.io/example-name: schema_registry_admin
  name: schema-registry-admin
spec:
  forProvider:
    clusterApiUrl: ${redpanda_cluster.example.cluster_api_url}
    host: '*'
    operation: ALTER
    permissionType: ALLOW
    principal: schema-user
    resourceName: kafka-cluster
    resourcePatternType: LITERAL
    resourceType: CLUSTER

---

apiVersion: redpanda.redpanda.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/registryacl
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cloudProvider: aws
    clusterType: dedicated
    connectionType: public
    name: example-cluster
    networkId: ${redpanda_network.example.id}
    region: us-west-2
    resourceGroupId: ${redpanda_resource_group.example.id}
    throughputTier: tier-1-aws
    zones:
    - us-west-2a
    - us-west-2b
    - us-west-2c

---

apiVersion: redpanda.redpanda.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/registryacl
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cidrBlock: 10.0.0.0/20
    cloudProvider: aws
    clusterType: dedicated
    name: example-network
    region: us-west-2
    resourceGroupId: ${redpanda_resource_group.example.id}

---

apiVersion: resource.redpanda.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/registryacl
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-resource-group

---

apiVersion: redpanda.redpanda.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: schema/v1alpha1/registryacl
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    allowDeletion: true
    clusterApiUrl: ${redpanda_cluster.example.cluster_api_url}
    mechanism: scram-sha-256
    name: schema-user
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
