apiVersion: serverless.redpanda.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: serverless/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-serverless-cluster
    region: us-west-2
    resourceGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: resource.redpanda.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: serverless/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-resource-group
