// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/crossplane-contrib/provider-redpanda/apis/cluster/redpanda/v1alpha1"
	v1alpha1resource "github.com/crossplane-contrib/provider-redpanda/apis/cluster/resource/v1alpha1"
	v1alpha1role "github.com/crossplane-contrib/provider-redpanda/apis/cluster/role/v1alpha1"
	v1alpha1schema "github.com/crossplane-contrib/provider-redpanda/apis/cluster/schema/v1alpha1"
	v1alpha1serverless "github.com/crossplane-contrib/provider-redpanda/apis/cluster/serverless/v1alpha1"
	v1alpha1cluster "github.com/crossplane-contrib/provider-redpanda/apis/cluster/v1alpha1"
	v1beta1 "github.com/crossplane-contrib/provider-redpanda/apis/cluster/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1resource.SchemeBuilder.AddToScheme,
		v1alpha1role.SchemeBuilder.AddToScheme,
		v1alpha1schema.SchemeBuilder.AddToScheme,
		v1alpha1serverless.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
