// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AssignmentInitParameters struct {

	// (String) The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster
	// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/redpanda/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("cluster_api_url",true)
	ClusterAPIURL *string `json:"clusterApiUrl,omitempty" tf:"cluster_api_url,omitempty"`

	// Reference to a Cluster in redpanda to populate clusterApiUrl.
	// +kubebuilder:validation:Optional
	ClusterAPIURLRef *v1.Reference `json:"clusterApiUrlRef,omitempty" tf:"-"`

	// Selector for a Cluster in redpanda to populate clusterApiUrl.
	// +kubebuilder:validation:Optional
	ClusterAPIURLSelector *v1.Selector `json:"clusterApiUrlSelector,omitempty" tf:"-"`

	// (String) The principal to assign the role to. Specify just the username (e.g., "john.doe")
	// The principal to assign the role to. Specify just the username (e.g., `"john.doe"`)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/redpanda/v1alpha1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Reference to a User in redpanda to populate principal.
	// +kubebuilder:validation:Optional
	PrincipalRef *v1.Reference `json:"principalRef,omitempty" tf:"-"`

	// Selector for a User in redpanda to populate principal.
	// +kubebuilder:validation:Optional
	PrincipalSelector *v1.Selector `json:"principalSelector,omitempty" tf:"-"`

	// (String) The name of the role to assign
	// The name of the role to assign
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type AssignmentObservation struct {

	// (String) The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster
	// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster
	ClusterAPIURL *string `json:"clusterApiUrl,omitempty" tf:"cluster_api_url,omitempty"`

	// (String) The ID of this resource. Format: {role_name}:{principal}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The principal to assign the role to. Specify just the username (e.g., "john.doe")
	// The principal to assign the role to. Specify just the username (e.g., `"john.doe"`)
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// (String) The name of the role to assign
	// The name of the role to assign
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type AssignmentParameters struct {

	// (String) The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster
	// The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/redpanda/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("cluster_api_url",true)
	// +kubebuilder:validation:Optional
	ClusterAPIURL *string `json:"clusterApiUrl,omitempty" tf:"cluster_api_url,omitempty"`

	// Reference to a Cluster in redpanda to populate clusterApiUrl.
	// +kubebuilder:validation:Optional
	ClusterAPIURLRef *v1.Reference `json:"clusterApiUrlRef,omitempty" tf:"-"`

	// Selector for a Cluster in redpanda to populate clusterApiUrl.
	// +kubebuilder:validation:Optional
	ClusterAPIURLSelector *v1.Selector `json:"clusterApiUrlSelector,omitempty" tf:"-"`

	// (String) The principal to assign the role to. Specify just the username (e.g., "john.doe")
	// The principal to assign the role to. Specify just the username (e.g., `"john.doe"`)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-redpanda/apis/cluster/redpanda/v1alpha1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Reference to a User in redpanda to populate principal.
	// +kubebuilder:validation:Optional
	PrincipalRef *v1.Reference `json:"principalRef,omitempty" tf:"-"`

	// Selector for a User in redpanda to populate principal.
	// +kubebuilder:validation:Optional
	PrincipalSelector *v1.Selector `json:"principalSelector,omitempty" tf:"-"`

	// (String) The name of the role to assign
	// The name of the role to assign
	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

// AssignmentSpec defines the desired state of Assignment
type AssignmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AssignmentInitParameters `json:"initProvider,omitempty"`
}

// AssignmentStatus defines the observed state of Assignment.
type AssignmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Assignment is the Schema for the Assignments API. A role assignment is used for attaching one user to a role.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,redpanda}
type Assignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleName) || (has(self.initProvider) && has(self.initProvider.roleName))",message="spec.forProvider.roleName is a required parameter"
	Spec   AssignmentSpec   `json:"spec"`
	Status AssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AssignmentList contains a list of Assignments
type AssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Assignment `json:"items"`
}

// Repository type metadata.
var (
	Assignment_Kind             = "Assignment"
	Assignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Assignment_Kind}.String()
	Assignment_KindAPIVersion   = Assignment_Kind + "." + CRDGroupVersion.String()
	Assignment_GroupVersionKind = CRDGroupVersion.WithKind(Assignment_Kind)
)

func init() {
	SchemeBuilder.Register(&Assignment{}, &AssignmentList{})
}
